classdef MshTest < matlab.unittest.TestCase
    % MshTest: unit tests of Node, Edge, Elem, Msh, mshD2TS, Msh.auto, mshSplit and checkMsh.
    methods (Test, TestTags = {'Fast'})
        function handBuilt(tc)
            node = Node([0, 1; 1, 1; 0, 2; 1, 2]', [-1, -2, -4, -3]);
            elem = Elem([2, 3, 1; 3, 2, 4]', [5, 3, 1; -5, 4, 2]', [5, 7]);
            edge = Edge([1, 2; 4, 3; 3, 1; 2, 4; 2, 3]', [1, 0; 2, 0; 1, 0; 2, 0; 1, -2]', [1, 3, 4, 2, 0]);
            tc.verifyEqual([node.dim, node.nNode], [2, 4]);
            tc.verifyEqual([elem.nElem, elem.nNode, elem.nEdge], [2, 3, 3]);
            tc.verifyEqual([edge.nEdge, edge.nNode, edge.nElem], [5, 2, 2]);
            msh = Msh("D2T", node, elem, edge);
            tc.verifyEqual(msh.dim, 2);
            tc.verifyEqual([msh.nNode, msh.nEdge, msh.nElem], [4, 5, 2]);
            tc.verifyEqual([msh.nEnt(0), msh.nEnt(1), msh.nEnt(2)], [4, 5, 2]);
            [flag, msg] = checkMsh(msh, "vol", 1);
            tc.verifyTrue(flag, msg);
            % Every boundary edge takes part in boundary integral: perimeter is 4.
            P1_FES = FES(msh, FE("D2T", "[1,x,y]", NdDoF("D2", MshEnt("D2T").msh, 0, [], [0; 0])));
            [~, F] = assemble(msh, P1_FES, P1_FES, DLF.empty, SLF(msh, 1, Fcn.cst(1), [0; 0], "EntIdx", find(edge.type ~= 0), ...
                "GInt", GInt("D2L", 1)));
            tc.verifyEqual(sum(F), 4, "AbsTol", 1e-12);
        end
        function D1(tc)
            msh = Msh("D1", Node([0, 1, 2]), Elem([1, 2; 2, 3]'));
            tc.verifyEqual(msh.dim, 1);
            tc.verifyEqual([msh.nEnt(0), msh.nEnt(1)], [3, 2]);
        end
        function dimHelper(tc)
            % Dimension-agnostic helpers: ent, domn, ElDomn, FtDomn, FtRefDomn, facet.
            msh = mshD2TS([0, 1, 0, 1], 2);
            tc.verifyEqual(msh.domn, "D2");
            tc.verifyEqual(msh.ElDomn, "D2T");
            tc.verifyEqual(msh.FtDomn, "D2L");
            tc.verifyEqual(msh.FtRefDomn, "D2LR");
            tc.verifyEqual(msh.facet, msh.edge);
            tc.verifyEqual(msh.ent(0), msh.node);
            tc.verifyEqual(msh.ent(1), msh.edge);
            tc.verifyEqual(msh.ent(2), msh.elem);
            % EntDim = 3 is valid only for 3D mesh.
            tc.verifyError(@() msh.ent(3), ?MException);
            tc.verifyError(@() msh.nEnt(3), ?MException);
            tc.verifyError(@() msh.ent(4), "MATLAB:validators:mustBeMember");
            msh = Msh("D1", Node([0, 1, 2]), Elem([1, 2; 2, 3]'));
            tc.verifyEqual(msh.ent(0), msh.node);
            tc.verifyEqual(msh.ent(1), msh.elem);
            tc.verifyEqual(msh.domn, "VOID");
            tc.verifyEqual(msh.ElDomn, "VOID");
            tc.verifyEqual(msh.FtDomn, "VOID");
            tc.verifyEqual(msh.FtRefDomn, "VOID");
            tc.verifyEmpty(msh.facet);
        end
        function bdEntity(tc)
            % Entities on facets with specified types, compared with node and edge types of mshD2TS.
            msh = mshD2TS([0, 1, 0, 1], 4);
            tc.verifyEqual(msh.bdEnt(0, [1, 2]), find(ismember(msh.node.type, [1, 2, -1, -2, -3])));
            tc.verifyEqual(msh.bdEnt(1, [1, 2]), find(ismember(msh.edge.type, [1, 2])));
            tc.verifyEqual(msh.bdEnt(0, [3, 4]), find(ismember(msh.node.type, [3, 4, -1, -3, -4])));
            tc.verifyEqual(msh.bdEnt(0, 1:4), find(msh.node.type ~= 0));
            % Elements connected to lower boundary.
            tc.verifyEqual(msh.bdEnt(2, 1), [1, 3, 5, 7]);
            tc.verifyEmpty(msh.bdEnt(0, 9));
            % Edges generated by Alfeld splitting connect barycenters to all nodes.
            msh = mshSplit(msh);
            tc.verifyEqual(msh.bdEnt(1, 1i), find(msh.edge.type == 1i));
            tc.verifyEqual(msh.bdEnt(0, 1i), 1:msh.nNode);
        end
        function structured(tc)
            msh = mshD2TS([0, 1, 3, 4], [2, 3]);
            tc.verifyEqual(msh.type, "D2T");
            tc.verifyEqual([msh.nNode, msh.nEdge, msh.nElem], [12, 23, 12]);
            [flag, msg] = checkMsh(msh, "vol", 1);
            tc.verifyTrue(flag, msg);
            % Node type: interior 0, boundary 1..4, corner -1..-4.
            tc.verifyEqual(sort(msh.node.type), [-4, -3, -2, -1, 0, 0, 1, 2, 2, 3, 4, 4]);
            % Edge type: 13 interior, 2 lower, 3 right, 2 upper, 3 left.
            tc.verifyEqual(histcounts(msh.edge.type, -0.5:1:4.5), [13, 2, 3, 2, 3]);
            % Coordinates of boundary nodes.
            crd = msh.node.coord;
            tc.verifyTrue(all(abs(crd(2, msh.node.type == 1) - 3) < 1e-14));
            tc.verifyTrue(all(abs(crd(1, msh.node.type == 2) - 1) < 1e-14));
            tc.verifyTrue(all(abs(crd(2, msh.node.type == 3) - 4) < 1e-14));
            tc.verifyTrue(all(abs(crd(1, msh.node.type == 4) - 0) < 1e-14));
            for n = [1, 2, 4, 8]
                [flag, msg] = checkMsh(mshD2TS([0, 1, 0, 1], n), "vol", 1);
                tc.verifyTrue(flag, sprintf("nSub = %d: %s", n, msg));
            end
        end
        function autoMsh(tc)
            msh0 = mshD2TS([0, 1, 3, 4], [2, 3]);
            msh = Msh.auto("D2T", msh0.node, msh0.elem.node);
            tc.verifyEqual([msh.nNode, msh.nEdge, msh.nElem], [12, 23, 12]);
            [flag, msg] = checkMsh(msh, "vol", 1);
            tc.verifyTrue(flag, msg);
            tc.verifyEqual(msh.elem.node, msh0.elem.node);
            % Same edges with same types.
            [EgKey0, idx0] = sortrows(sort(msh0.edge.node, 1)');
            [EgKey, idx] = sortrows(sort(msh.edge.node, 1)');
            tc.verifyEqual(EgKey, EgKey0);
            tc.verifyEqual(msh.edge.type(idx), msh0.edge.type(idx0));
            % Clockwise input elements are reoriented.
            ElNode = msh0.elem.node;
            ElNode([2, 3], 1:2:end) = ElNode([3, 2], 1:2:end);
            msh = Msh.auto("D2T", msh0.node, ElNode);
            [flag, msg] = checkMsh(msh, "vol", 1);
            tc.verifyTrue(flag, msg);
        end
        function splitMsh(tc)
            msh0 = mshD2TS([0, 1, 3, 4], [2, 3]);
            msh = mshSplit(msh0);
            tc.verifyEqual([msh.nNode, msh.nEdge, msh.nElem], [24, 59, 36]);
            [flag, msg] = checkMsh(msh, "vol", 1);
            tc.verifyTrue(flag, msg);
            tc.verifyEqual(nnz(msh.node.type == 1i), 12);
            tc.verifyEqual(nnz(msh.edge.type == 1i), 36);
            % Barycenter nodes.
            for iElem = 1:msh0.nElem
                tc.verifyEqual(msh.node.coord(:, msh0.nNode + iElem), mean(msh0.node.coord(:, msh0.elem.node(:, iElem)), 2), ...
                    "AbsTol", 1e-14);
            end
        end
        function checkCorrupt(tc)
            % checkMsh detects corrupted mesh data.
            msh0 = mshD2TS([0, 1, 0, 1], 2);
            msh = msh0;
            msh.elem.node([2, 3], 1) = msh.elem.node([3, 2], 1);
            tc.verifyFalse(checkMsh(msh));
            msh = msh0;
            msh.elem.edge(1, 1) = -msh.elem.edge(1, 1);
            tc.verifyFalse(checkMsh(msh));
            msh = msh0;
            msh.edge.elem(:, 5) = -msh.edge.elem(:, 5);
            tc.verifyFalse(checkMsh(msh));
            msh = msh0;
            msh.edge.type(1) = 0;
            tc.verifyFalse(checkMsh(msh));
            tc.verifyTrue(checkMsh(msh, "bdType", false));
            tc.verifyFalse(checkMsh(msh0, "vol", 2));
        end
        function singleTet(tc)
            % Single tetrahedron, input in negative orientation.
            node = Node([0, 1, 0, 0; 0, 0, 1, 0; 0, 0, 0, 1]);
            msh = Msh.auto("D3T", node, [1; 2; 4; 3]);
            tc.verifyEqual(msh.type, "D3T");
            tc.verifyEqual(msh.dim, 3);
            tc.verifyEqual(msh.elem.node, [1; 2; 3; 4]);
            tc.verifyEqual([msh.nNode, msh.nEdge, msh.nFace, msh.nElem], [4, 6, 4, 1]);
            tc.verifyEqual([msh.nEnt(0), msh.nEnt(1), msh.nEnt(2), msh.nEnt(3)], [4, 6, 4, 1]);
            tc.verifyEqual(sort(msh.elem.face)', 1:4);
            tc.verifyTrue(all(msh.elem.face > 0) && all(msh.elem.facePerm == 1));
            tc.verifyEqual(msh.face.type, ones(1, 4));
            [flag, msg] = checkMsh(msh, "vol", 1/6);
            tc.verifyTrue(flag, msg);
        end
        function twoTet(tc)
            % Two tetrahedra sharing face [2, 3, 4].
            node = Node([0, 1, 0, 0, 1; 0, 0, 1, 0, 1; 0, 0, 0, 1, 1]);
            msh = Msh.auto("D3T", node, [1, 2, 3, 4; 2, 3, 4, 5]');
            tc.verifyEqual([msh.nNode, msh.nEdge, msh.nFace, msh.nElem], [5, 9, 7, 2]);
            [flag, msg] = checkMsh(msh, "vol", 1/6 + 1/3);
            tc.verifyTrue(flag, msg);
            % Shared face: positive in one element and negative in the other.
            isInt = all(msh.face.elem ~= 0, 1);
            tc.verifyEqual(nnz(isInt), 1);
            tc.verifyEqual(sort(msh.face.elem(:, isInt))', [-2, 1]);
        end
        function structured3D(tc)
            % Counts of nodes, edges, faces, elements and boundary faces (12 n^2).
            cnt = [8, 19, 18, 6; 27, 98, 120, 48; 64, 279, 378, 162];
            for n = 1:3
                msh = mshD3TS([0, 1, 0, 1, 0, 1], n);
                tc.verifyEqual([msh.nNode, msh.nEdge, msh.nFace, msh.nElem], cnt(n, :));
                [flag, msg] = checkMsh(msh, "vol", 1);
                tc.verifyTrue(flag, sprintf("nSub = %d: %s", n, msg));
                tc.verifyEqual(histcounts(msh.face.type, 0.5:1:6.5), 2 * n^2 * ones(1, 6));
            end
            msh = mshD3TS([0, 2, 0, 1, 0, 3], [2, 1, 3]);
            tc.verifyEqual([msh.nNode, msh.nEdge, msh.nFace, msh.nElem], [24, 81, 94, 36]);
            [flag, msg] = checkMsh(msh, "vol", 6);
            tc.verifyTrue(flag, msg);
            % Boundary faces of each type lie on the corresponding side.
            crd = msh.node.coord;
            side = [0, 2, 0, 1, 0, 3];
            for iType = 1:6
                FcNd = msh.face.node(:, msh.face.type == iType);
                iDim = ceil(iType / 2);
                tc.verifyTrue(all(abs(crd(iDim, FcNd) - side(iType)) < 1e-14), sprintf("Face type %d.", iType));
            end
        end
        function dimHelper3D(tc)
            msh = mshD3TS([0, 1, 0, 1, 0, 1], 2);
            tc.verifyEqual(msh.domn, "D3");
            tc.verifyEqual(msh.ElDomn, "D3T");
            tc.verifyEqual(msh.FtDomn, "D3F");
            tc.verifyEqual(msh.FtRefDomn, "D3FR");
            tc.verifyEqual(msh.facet, msh.face);
            tc.verifyEqual(msh.ent(1), msh.edge);
            tc.verifyEqual(msh.ent(2), msh.face);
            tc.verifyEqual(msh.ent(3), msh.elem);
            % Entities on boundary x = 0 (type 1).
            crd = msh.node.coord;
            BdNode = msh.bdEnt(0, 1);
            tc.verifyEqual(BdNode, find(abs(crd(1, :)) < 1e-14));
            BdEdge = msh.bdEnt(1, 1);
            tc.verifyEqual(length(BdEdge), 16);
            tc.verifyTrue(all(abs(crd(1, msh.edge.node(:, BdEdge))) < 1e-14, "all"));
            tc.verifyEqual(length(msh.bdEnt(2, 1)), 8);
            tc.verifyEqual(length(msh.bdEnt(3, 1)), 8);
            tc.verifyEqual(length(msh.bdEnt(0, 1:6)), 26);
            % Reference tetrahedron.
            tc.verifyEqual(MshEnt("D3T").msh.type, "D3T");
            tc.verifyEqual(MshEnt("D3TR").msh.nElem, 1);
        end
        function relabel3D(tc)
            % Random node relabeling and random even permutations of local vertices (orientation kept):
            % all invariants still hold, and odd face permutations 4, 5, 6 occur.
            msh0 = mshD3TS([0, 1, 0, 1, 0, 1], 2);
            rng(0);
            nodePerm = randperm(msh0.nNode);
            invPerm(nodePerm) = 1:msh0.nNode;
            ElNode = invPerm(msh0.elem.node);
            I = eye(4); P4 = perms(1:4);
            evenPerm = P4(arrayfun(@(i) det(I(P4(i, :), :)) > 0, 1:size(P4, 1)), :);
            for iElem = 1:msh0.nElem
                ElNode(:, iElem) = ElNode(evenPerm(randi(size(evenPerm, 1)), :), iElem);
            end
            msh = Msh.auto("D3T", Node(msh0.node.coord(:, nodePerm)), ElNode);
            tc.verifyEqual([msh.nNode, msh.nEdge, msh.nFace, msh.nElem], [27, 98, 120, 48]);
            [flag, msg] = checkMsh(msh, "vol", 1);
            tc.verifyTrue(flag, msg);
            tc.verifyTrue(all(ismember(4:6, msh.elem.facePerm(:))));
        end
        function checkCorrupt3D(tc)
            msh0 = mshD3TS([0, 1, 0, 1, 0, 1], 1);
            tc.verifyTrue(checkMsh(msh0));
            msh = msh0;
            msh.elem.node([3, 4], 1) = msh.elem.node([4, 3], 1);
            tc.verifyFalse(checkMsh(msh));
            msh = msh0;
            msh.elem.facePerm(1, 1) = mod(msh.elem.facePerm(1, 1), 3) + 1;
            tc.verifyFalse(checkMsh(msh));
            msh = msh0;
            msh.face.elem(:, 1) = -msh.face.elem(:, 1);
            tc.verifyFalse(checkMsh(msh));
            msh = msh0;
            msh.face.node([2, 3], 1) = msh.face.node([3, 2], 1);
            tc.verifyFalse(checkMsh(msh));
            msh = msh0;
            msh.face.edge(1, 1) = -msh.face.edge(1, 1);
            tc.verifyFalse(checkMsh(msh));
        end
        function plotMsh(tc)
            msh = mshD2TS([0, 1, 0, 1], 2);
            nFig = length(findall(groot, "Type", "figure"));
            msh.figure;
            fig = findall(groot, "Type", "figure");
            tc.verifyEqual(length(fig), nFig + 1);
            close(fig(1));
        end
    end
end
