classdef Regression2DTest < matlab.unittest.TestCase
    % Regression2DTest: compare 2D results with baseline generated by makeBaseline2D.

    % Data    | Tolerance                                    | Tag
    % ------- | -------------------------------------------- | ----------------
    % small   | absolute 1e-10 * max(1, max(abs(baseline))) | Fast, Regression
    % example | relative 1e-4 (printed with 6 digits)       | Slow, Regression

    properties
        base; % Baseline data.
    end
    methods (TestClassSetup)
        function loadBase(tc)
            file = fullfile(fileparts(fileparts(mfilename("fullpath"))), "baseline", "baseline_2D.mat");
            tc.assumeTrue(isfile(file), "Baseline not found: run makeBaseline2D on unmodified 2D code first.");
            tc.base = load(file);
        end
    end
    methods (Test, TestTags = {'Fast', 'Regression'})
        function smallMesh(tc)
            act = calcRegression2D("small", true, "example", false);
            cmpData(tc, act.small, tc.base.data.small, "small", "abs");
        end
    end
    methods (Test, TestTags = {'Slow', 'Regression'})
        function example(tc)
            tc.assumeTrue(isfield(tc.base.data, "example"), "Baseline has no example data.");
            act = calcRegression2D("small", false, "example", true);
            cmpData(tc, act.example, tc.base.data.example, "example", "rel");
        end
    end
end
%% Local functions.
function cmpData(tc, act, ref, path, tolType)
    % cmpData: compare data recursively.
    if isstruct(ref)
        tc.verifyTrue(isstruct(act), path + ": not a struct.");
        if ~isstruct(act)
            return;
        end
        tc.verifyEqual(sort(string(fieldnames(act))), sort(string(fieldnames(ref))), path + ": fields differ.");
        name = fieldnames(ref);
        for iName = 1:length(name)
            if isfield(act, name{iName})
                cmpData(tc, act.(name{iName}), ref.(name{iName}), path + "." + name{iName}, tolType);
            end
        end
    else
        act = full(double(act));
        ref = full(double(ref));
        tc.verifyEqual(size(act), size(ref), path + ": size differs.");
        if isequal(size(act), size(ref))
            switch tolType
                case "abs"
                    tc.verifyEqual(act, ref, "AbsTol", 1e-10 * max([1; abs(ref(:))]), path);
                case "rel"
                    tc.verifyEqual(act, ref, "RelTol", 1e-4, path);
            end
        end
    end
end
